# Generated by Django 5.1 on 2024-10-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomV', models.CharField(max_length=100)),
                ('descriptionV', models.TextField()),
                ('imageV', models.ImageField(upload_to='images/', verbose_name='imageVille')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
