# Generated by Django 5.1 on 2024-10-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_ville_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='nomV',
            field=models.CharField(max_length=255),
        ),
    ]
