# Generated by Django 5.1 on 2024-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_ville_latitude_ville_longitude_alter_ville_nomv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville',
            name='imageV',
        ),
        migrations.AddField(
            model_name='ville',
            name='imageCH',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='imagechambre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ville',
            name='imageM',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='imageMaison'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ville',
            name='imageQ',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='imageQuantier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ville',
            name='nomQ',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ville',
            name='numM',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
