# Generated by Django 5.1 on 2024-10-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_remove_ville_imagev_ville_imagech_ville_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='imageCH',
            field=models.ImageField(upload_to='images/chambres/', verbose_name='imagechambre'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='imageM',
            field=models.ImageField(upload_to='images/maisons/', verbose_name='imageMaison'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='imageQ',
            field=models.ImageField(upload_to='images/quantier/', verbose_name='imageQuantier'),
        ),
    ]
