# Generated by Django 5.1 on 2024-10-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_client_visite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_naissance',
        ),
    ]
