# Generated by Django 5.1 on 2024-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0007_remove_client_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sexe',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
